# Generated by Django 4.2.7 on 2024-01-16 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=255)),
                ('document_reference', models.CharField(editable=False, max_length=255)),
                ('purchase_request_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('location_required', models.CharField(choices=[('location1', 'Location 1'), ('location2', 'Location 2')], max_length=255)),
                ('date_required', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved_first', 'First Approval'), ('approved_second', 'Second Approval'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('donor', models.CharField(blank=True, choices=[('donor1', 'Donor 1'), ('donor2', 'Donor 2')], max_length=255, null=True)),
                ('budget_line', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.item')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('type1', 'User Type 1'), ('type2', 'Budget Holder'), ('type3', 'Finance Checker')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('first', 'First Approval'), ('second', 'Second Approval')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_made', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='finance.purchaserequest')),
            ],
        ),
    ]
