# Generated by Django 4.2.7 on 2024-01-17 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('user', 'Regular User'), ('budget_holder', 'Budget Holder'), ('finance_checker', 'Finance Checker')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='document_reference',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='location_required',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purchase_request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_budget_holder', 'Approved by Budget Holder'), ('approved_finance_checker', 'Approved by Finance Checker'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
