# Generated by Django 4.2.7 on 2024-01-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_profile_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('day', 'Day'), ('flights', 'Flights'), ('number', 'Number'), ('months', 'Months'), ('times', 'Times'), ('liter', 'Liter'), ('kg', 'Kg'), ('pcs', 'Pieces'), ('trip', 'Trip'), ('lump_sum', 'Lump Sum'), ('none', 'none')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budgetline'),
        ),
    ]
