# Generated by Django 4.2.7 on 2024-01-30 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budgetline_alter_item_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
