# Generated by Django 4.2.7 on 2024-02-04 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_alter_budgetline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='donor',
            field=models.CharField(blank=True, choices=[('N62', 'N62'), ('donor2', 'Donor 2')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_on', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved_budget_holder', 'Approved by Budget Holder'), ('approved_finance_checker', 'Approved by Finance Checker'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.purchaserequest')),
            ],
        ),
    ]
