# Generated by Django 4.2.6 on 2023-11-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.employee')),
                ('total_leaves', models.PositiveIntegerField(default=0)),
                ('used_leaves', models.PositiveIntegerField(default=0)),
                ('remaining_leaves', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveType', models.CharField(choices=[('sick', 'Sick Leave'), ('paid', 'paid leave'), ('unpaid', 'Unpaid Leave')], default='paid', max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
