# Generated by Django 4.2.6 on 2023-10-31 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('MiddleName', models.CharField(blank=True, max_length=255, null=True)),
                ('DateHired', models.DateField(blank=True, null=True)),
                ('DateOfBirth', models.DateField()),
                ('Nationality', models.CharField(max_length=255)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=15, unique=True)),
                ('InsuranceNumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('PassportNumber', models.CharField(max_length=255, unique=True)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='PositionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.employee')),
                ('AddressDescription', models.TextField(blank=True)),
                ('Street', models.TextField()),
                ('City', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.department')),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.positionlevel')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.position'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('DependentID', models.AutoField(primary_key=True, serialize=False)),
                ('DependentName', models.CharField(blank=True, max_length=255, null=True)),
                ('Relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent')], max_length=20)),
                ('DateOfBirth', models.DateField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address'),
        ),
    ]
